
# This file is part of c'mon, a lightweight telephony monitor.
#
# Copyright (C) 2012 Peter Schaefer-Hutter ("THE AUTHOR")
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# ----------------------------------------------------------------------------
# NOTE: This License does NOT permit incorporating this file (or parts or
#       changed versions of it) into proprietary programs that are
#       distributed to third-parties in binary form only.
# ----------------------------------------------------------------------------

# You can contact the original author by email at peter.schaefer@gmx.de
# if you need different license-terms or other modifications to c'mon.

# $Revision: 47 $ $Date: 2012-11-18 22:38:42 +0100 (Sun, 18 Nov 2012) $

import os

Import('env')
Import('WXLIBS')

env_local = env.Clone()

env_local.Append(CPPDEFINES = [ 'BUILDING_PLUGIN' ] )

env_local.Prepend(CPPPATH=['.'])

if GetOption('compiler') == "mingw":
  env_local['WINDOWS_INSERT_DEF'] = 1
  env_local['GchSh'] = env_local.Gch('#plugin_cp_dummy/stdwx.h')[0]
elif GetOption('compiler') == 'msvc':
  env_local['PCH'] = env_local.PCH('stdwx.cpp')[0]
  env_local['PCHSTOP'] = 'stdwx.h'

lib_sources = Glob('cpd_*.cpp')

libTarget = env_local.SharedLibrary(
            target = 'hzcpdummy', 
            source = lib_sources,
            LIBS = WXLIBS + [  
                     'comctl32', 
                     'uuid', 
                     'rpcrt4',
                     'kernel32',
                     'user32',
                     'gdi32',
                     'winspool',
                     'comdlg32',
                     'advapi32',
                     'shell32',
                     'hzshared'
                    ]
            )

env_local.Alias("install", env_local.Install(os.path.join("..", "plugins"), libTarget))
