
# This file is part of c'mon, a lightweight telephony monitor.
#
# Copyright (C) 2012 Peter Schaefer-Hutter ("THE AUTHOR")
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# ----------------------------------------------------------------------------
# NOTE: This License does NOT permit incorporating this file (or parts or
#       changed versions of it) into proprietary programs that are
#       distributed to third-parties in binary form only.
# ----------------------------------------------------------------------------

# You can contact the original author by email at peter.schaefer@gmx.de
# if you need different license-terms or other modifications to c'mon.

# $Revision: 36 $ $Date: 2012-10-04 21:34:20 +0200 (Thu, 04 Oct 2012) $

import os

Import('env')
Import('WXLIBS')

env_local = env.Clone()

env_local.Prepend(CPPPATH=['.'])

env_local.Append(CPPPATH = [ os.path.join( '#third_party', 'icu-49-1-2', 'source', 'common' ),
                             os.path.join( '#third_party', 'icu-49-1-2', 'source', 'i18n' ) ])

env_local.Append(CPPDEFINES = [ 'BUILDING_SHARED' ] )

if GetOption('compiler') == "mingw":
    env_local['WINDOWS_INSERT_DEF'] = 1
    env_local['GchSh'] = env.Gch('#shared/src/stdwx.h')[0]

lib_sources = Glob('src/*.cpp')

boost_libs = [  ]
if GetOption('compiler') == "mingw":
  if GetOption('build_kind') == "debug":
    boost_libs = [ 'libboost_system-mgw47-mt-d-1_51' ]
  elif GetOption('build_kind') == "release":
    boost_libs = [ 'libboost_system-mgw47-mt-1_51' ]

libTarget = env_local.SharedLibrary(
            target = 'hzshared', 
            source = lib_sources, 
            LIBS = WXLIBS + [
                     'comctl32', 
                     'uuid', 
                     'rpcrt4',
                     'kernel32',
                     'user32',
                     'gdi32',
                     'winspool',
                     'comdlg32',
                     'advapi32',
                     'shell32',
                     'phonenumber',
                     'icuuc49', 
                     'icuin49',
                     'protobuf'
                    ] + boost_libs
            )

env_local.Alias("install", env_local.Install("..", libTarget))
